language: android
sudo: required
dist: trusty

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=28.0.3

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - '.+'

script: gradle clean test

before_install:
  - yes | sdkmanager "platforms;android-28"
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip -qq gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
